apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  project: default
  source:
    repoURL: https://github.com/manueljishi/homelab.git
    targetRevision: HEAD
    path: manifests/transmission
  destination:
    server: https://kubernetes.default.svc
    namespace: default